### ISSUE TITLE
Add recipe (breakdown)

### ISSUE THREAD

**Issue by Solomon-Coding** [Solomon-Coding/Homecooked#30]

**Comment by justindevs** [comment]
- [ ] create handlebars template with a form and submit button
- [ ] create a js file in public/js that has a handler function to make a POST fetch to create the recipe and on success redirects user back to home
- [ ] create an endpoint to render the addRecipe HTML to send to the front end
- [ ] create an API endpoint that is a POST /api/recipe and uses sequelize to create the new database entry
